### ISSUE TITLE
USER STORY: Approve comments

### ISSUE THREAD

**Issue by AnaD30** [AnaD30/bookreviewpage-p4#4]
As a **Site Admin** I can **approve or disapprove comments** so that I can **filter out objectionable comments**.

### Acceptance Criteria

-    Acceptance Criteria 1:the comments should appear on the book page under the description
-    Acceptance Criteria 2: the admin should operate on certain days
-    Acceptance Criteria 3: remove options or delete next to submit

### Tasks:

- [ ] update the admin view adjust the design(HTML and CSS) include a checkbox for closing the comment section
- [ ] update the website view after removing the comments
- [ ] test the functionality of the display

### Points:#4
